#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
xsetroot -cursor_name left_ptr

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V
bspc monitor DP-3 -d VI

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config focused_border_color     "#4274a5"
bspc config normal_border_color      "#202023"

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a LibreWolf state=tiled desktop='^2' follow=on
